server:
  port: 8088

#logging:
#  level:
#    org.springframework: debug

spring:
  message:
    basename: messages
#  security:
#    user:
#      name: username
#      password: passw0rd

#spring:
#  application:
#    name: user-service

#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://127.0.0.1:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
